[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "4aa73ccc23ee98083fdcc68bbb835cdf2930a720"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "f7eaed3d330da27f96355ed920a2ea80f68e7db30b18f2a096af8344f5b0b515"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+7/SuiteSparse.v5.4.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "c2f248958d9d510335c5f1757d5df56cd4fcd5c7"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "7828693b9ff1a028302f5439d87091aff0b0582cba4c73a8c3d04d4dbf2c0e98"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+7/SuiteSparse.v5.4.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "43d46aabef905c2e11fd3c6d09043e01eb1fbe5d"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d01721fe21de5ce448deff37ac41b78509fac9f751d0fdb23a9e338cc1a60eac"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+7/SuiteSparse.v5.4.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "fcb64b0fb51cb1b2654df7ec1d6c50a1a8a106bd"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8d8a022eddc4faa7674fa68e42daa0746e9bbab3b6c3691924f96adfac640447"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+7/SuiteSparse.v5.4.0.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "b90846d97a2b46917cadcc2d01b2d8fa0ad73e19"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "6cde1e94c7c3b41145d0c8c6177cf0085af6a3f7476de319038405bf58162885"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+7/SuiteSparse.v5.4.0.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "1abf89c97b5764839f7b2fc796bdb3cb61fd2724"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "fb26b52b4be6c1e9e9438a3e12702330d1876e88d56e2da3794e8e78c8bf14c0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+7/SuiteSparse.v5.4.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "08964a3599abca8c1eac5da76480fd7d7cf5c0c6"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "fc57489a6f07a8d0fc91302cba2fb1fee29b1aef59d9e0784bf29f1eaf28e049"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+7/SuiteSparse.v5.4.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "81e0436a741e7519408f647284a26a9a24adfd2b"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "b44084196af4208ca702fefc9ada39b091a520e1b787d55f8d04a1ae59264092"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+7/SuiteSparse.v5.4.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "e313b5acd3dac0e3de3008c9693965d2152dedca"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "9173ccb7bdfc05350bce7516312aa550ee5c12a6a0b943df5ccbfd7f0ae4e8dc"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+7/SuiteSparse.v5.4.0.x86_64-apple-darwin14.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "75f87edd2ac52625ce15ce1b04e7d96b67a8296f"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "db435d985d32d022f72aaac337f595baa2718408bad041928356ccc721c8dd49"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+7/SuiteSparse.v5.4.0.x86_64-unknown-freebsd11.1.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "aa82c83eb8a0cb6132fe7a06106207330428c9cb"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "cc85fa70f9c62711cf4027aae94da8ae1319cdfe7c7e213f7d7b9b3a8929b269"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+7/SuiteSparse.v5.4.0.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "e69cb7909099cd9c68aeada4724715f0a0b10d50"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "3d11c89fee20f67e73afd0609478db7983d0f88c48125ce689f0c6e6e05c3260"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+7/SuiteSparse.v5.4.0.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "80f3b2c4b71db2f1d91dad187a2fe05c65c2f716"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "cceb2689f229bb676a68bf0868304496e2748ff55f12cbf5f3bbdf2fb0f9647a"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+7/SuiteSparse.v5.4.0.x86_64-w64-mingw32.tar.gz"
