[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "d1b2818870cdf2c6cf19c9c973bbc7a2b0758854"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "5d06a9641c2d23404720f7ddac3048c4ba134f074df4672a80d7b8e924fea57e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "ad117854280da64fcf1acf0ac9cce0bbd4682f3e"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8b521307d0633a72bc3b57c09a20c60b802c6a34f4b2a3277a1b7d75c2fe14da"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "18c93b1a60f15d23d743e5a515986b66e61287d6"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "ff63628ee462b188f50c2d377819b1087bd3a914bfb22a87fb288266ecdf276f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5163a9bf22b8933a72cb6455392a0ab12ad551c2"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "9bb38972e9f085966a2b16f917c5bd4bf6316f5766a982c8a28e63049292314b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bd186d10785eefda92d7bd915010f0e87cf89e35"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "cf5b3bfc1c6057ae67a3b3ea7a5de634954a6518e04560964d3047a746aeede0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6617ac9067d8a9c29b25cfbdf484b1279b860075"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "feed93c350a72986cfe157d49b52d6e682ea4838e218f563a6c125f78f67fca5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ff7ed3d18581cadc87d1c7110b8630571e3bd88"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "ad0537be1be0006ab34bc52bdd27533592985fbca975415ff65a209c271732dd"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "12a974b9294227fa841047c850ba4061f466a480"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "e504487344304e1b334f461074b884a010eab97a0c55873e825f421d38846656"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "6d7e3ddf544f861a684b10c8b987610c743124a3"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8e8e204aef02af0edb732aac1cbff79e65ea2db2049b1302480235c0f113cda8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "c415217e9a1f790917ce2db12889d4198d17bd01"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "ef8f60f9c858c5a8ce36f2a9f3b7be4e39df9f1e9efaba0f17962d9852723d85"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "60c9f67e18503221485221aab158e308f6bd6b9d"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "29601e62b431100537598b713044cad6fe75bc7304b146225067435a4803bfe9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "b5ebdefd7be53bf7c10c488d218d3b2b54ad930a"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "0a1104293f84e14dc7dff7a5c7a30fd648e9cd6c84ef72d84d460ca8534c3786"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "0074d356d4f7be05b547e8da6fad90b6db3103cf"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d7de330e7df74de817d23d1ac068356fad613d2538e4fa4511fd1586e0977f32"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "bd7bffcd1bf7835aedc247fe223f4bfab9e83ae0"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "7def0356dd63e36fb0f3c08e33c42d4c33affe05f588760c51ed431de8e35987"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "762d1292384f3025d56e1e8e0e1dd926ddf3a0af"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "01af7089fe169dec2e1bb60908fc5b79240ce9b5adaedb374583a5b7cf132700"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "910b19fb5078996656685de830f1c5a05326571d"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "63f8b60b3452c24ea8352311a0d99ce044ff011f436fe0297ea4a67d52ae5e30"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.x86_64-w64-mingw32.tar.gz"
