[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "8a6008954d6e574167f045ae085293b5bfde8f3c"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "0f0bfad2eec2a8e576a3c01ca16ceb284457680bbca50e3befe4343012b07ee6"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "d8fa126530702358beabe41c0134affc2343ee8e"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "6a5a149e46f3e4d6135bd8526da3ff9b993ebdfe9d6b895fd88dfa72fb6dc2e4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "ed9afdfefa08f0ee879d4a33eb9c5f731501ebd1"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "e06b99f8a2979635ac7585e9f7aa2c63243eefe7c5a4498abda4516ed3a73a09"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "b42d138b9fa40ba05dfce942aaa1e9761aa85e3c"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "328e7c118e542f13c616bcda97434beba31969c6e94bad8b74a07a6135304ea4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.aarch64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3db02f62fde7d99c363b471ef99d7d95ad02103d"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "cd6027e40d67fe29006ffe6fbf8ec23b31e5c53c3bb7a27d5647643898101b22"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "578971aeaa4fcd8cc77f38944e5b0029f48ab367"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "1ee07095774a0c88d1c392be640ba50c646f4cf00c57866123327dc2428c565f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aa6cab007f6a675ded9f159a6b9328640ce58568"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "aa41075896e38e0132c2e691c993668bfe4586a2a81d04e18cca277dc583c1a1"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "56b532613212c759fb73cc72da5dc5d823888454"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "164c1cfa0d48574f7640c2129bbb1be5dabb475b3abc17625d6fcf3069a4170c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "7272406b69d638278a9b837e80a59a651fee1b5b"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "88dbe3354a092b40d7fed35ae0173f9c6d5692259e3e18ac3e8f793223210eb9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "5a457e9e4308e26ba33ec70f426260ab451f621b"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "b5512a1733ffca61735ff16d29ddfcd1f7d2b7a6d5ea2b0ef424665e028ce285"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "70ca76cce2abc4059692e1179298bd85ab5d78c9"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "b07ff0dba90bf9727e82b42d6bb4a58c2940f1184e82729fdb206b43fd40bc50"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "c9dd36e91ee0bf352945b1eea1b9f490df33c21e"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c5082298f8e5e380b258d8ad191aff4e0ee634b4c886dfd2e97da92a100c59f0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "riscv64"
git-tree-sha1 = "b458e6f70c2968fed3650cbaa7465b1e1eb0e26a"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "434c7bcc26925b71044149b5ffb467bd6a058889c3ffa1c7fc7c349eb62ead3f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.riscv64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "d0d8b85dae665203ba413ff61c189eadeb0dedc2"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "fdf19d72080f851fdfd2730d42af2acded0c0c6f2fb07c9cf82b734a681c0a3e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "3455b5982cff966026e3f3fbd37f6b9b127206a9"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "9c6beea70d750c639e4aaca2e5d258737d4ed713793f47d3378089f7c31aee5c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "fe7200105790600c9a3d8d15307b73b08b2def86"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "ea6e64e5eac5ca6eb94cbbbded433f06fb63098d631add68775446e78e7e5059"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "f59f5523552ab09d6da4d4dd837f68a4c940c6ba"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "41f82bc54c96964d4697673b25dbb996e7a0f1c62fa7db51e3d3eea575ecc808"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "eef596a8807b854f46d7cc51c21319e7265c7b02"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "aa8426ba16229477c8c8c494607e7e713c9754a2730a45ea43f6ba5ed176a747"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.10.1+0/SuiteSparse.v7.10.1.x86_64-w64-mingw32.tar.gz"
