[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "b01ed695769633ff13d939cd8a09f93ef023d063"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8bc9871e401330d59a4c0fef7f56a56689dd375de3a6b9047f70798d632aafe7"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+4/SuiteSparse.v5.4.0.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "2a1ea9317c9966635e7d6563434a82de1f2fa9a5"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "6b3e3c4deb064f3a93bab89f91eabc77da5ca8dc73c9046bb0afcc00df178cf8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+4/SuiteSparse.v5.4.0.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "da8f5c3015bac3656d8b0ed176fc8564acd3dba8"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "e63efea864376993860fd8527019b66405771d7187ed958862476e4a80915e44"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+4/SuiteSparse.v5.4.0.x86_64-apple-darwin14.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "1d625feccfa30af2215d1d78c074f0314cd344f3"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "4d6c7768a51d6d304ab40f65bc55a9322a52042c6b40634e0f173ea8c1fcd6f9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+4/SuiteSparse.v5.4.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "5246db6e39c9308a9eac4d1e82a5e45760bde1c7"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "91ecffe678267f1a541142516f60879af194bfb900802b60da5e73de998ce07e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+4/SuiteSparse.v5.4.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "a27d77ebc6f737285d579a9595b208870e27ae8f"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "b8c26aec298aba079df8a8757a5906db48766f89466f00e43fab6b756488b60a"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+4/SuiteSparse.v5.4.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "8c3aec2b137e7127f9c3eb3c73e5697409a26b39"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "0f14ad8fab1d365767465f747dd9cae0315ab8fd758d2ce8e77eb76a0187de6b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+4/SuiteSparse.v5.4.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "2557785aaa9a12b364964b7ed77d0a773ad6a63c"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "1b4612e47ea0932eeb6df33758ce7d86673ceb846b82747a5f6383355bae1ea5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+4/SuiteSparse.v5.4.0.arm-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "e082284e0a29a950b24a5a1817e7eef7247ccb7c"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "5ba9ee7f7f24a3f49bff2a70ae22f5295ed9177779b3f623c78ef2ced3cd400d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+4/SuiteSparse.v5.4.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "f816272c17ba63c18677a62268c22d5162c101df"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "355e4209c01b8787f437b4417fcd57f0dc2a1e29ffdc0020d0cf83bf869c0aa6"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+4/SuiteSparse.v5.4.0.x86_64-unknown-freebsd11.1.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "eb706a1d4a65668df935aab7b031e432a3de3791"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "0791f34aa01f78dabff110dada9b5fd3c2ba94e55f10284d1748d25c472ff684"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+4/SuiteSparse.v5.4.0.arm-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "f8edc6946239c2b68df857d354cd02bf0c8a4df3"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "1883e6215055303eb18b4fc49ff8a10e88ead5598089b382b68ccbfd17cf1ed4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+4/SuiteSparse.v5.4.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "e177c77afc4dbd274277508bd5d069731bbe517e"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "411870da868a532b3be1c173ded540e650534496c8b9a1e31fb0798575436cfa"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+4/SuiteSparse.v5.4.0.x86_64-w64-mingw32.tar.gz"
