[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "9485feb01771f1e42ec338467817fc639385d0d2"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "88c821028ad8578445f4782189fa2dcd0b5b1cd193b78dc00c1c3bef394bfc25"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "94bd680862e57e6c7e6fe2c782ab553121e9e97e"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8855bbd7f7ef489707a35cd0555a573f43ba5958965a3b283b6f058e73cf6104"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "31460cc3419a7d9c3e544ebdc9189c5471101c66"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8fc6aca0c863e42a06bc9c2adedac28766deba8180c4f6fd617040dd9e864e49"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9480ff3938caa3d1e794b41fbc5b4270647f9854"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "b932ca1da4b36dec605dfa493c0aeadb6d5dfb008463077930a6f3400033229a"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0a5057f4726300317f1275d173a81d96ee41dbda"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "13c60945e66ce15734116b3f1401dfb36d9ab3f037e8e5adcfbdf1cb5737d63e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4a313c6b9eac1a59cec3955df6fb1207ec01a32b"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d5ddb5b23edbf9e41a208a5e0c2b91c1c3770be053579457326eca29b9be134f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d75c16bb55cb11351d6388d7ac80b436e3c32759"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "6509e1720e310d628ba06eca0d1f7ba3767f45a46c2e96053909db81dddb37ac"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "fdf507139bdd83a3e1209a8c0a30542f6cd48554"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "002944451e49f34c583d053e624018883fca83118fbf855a3770c3414186c8a4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "f8527d8870d33e798ed13d31eac651438ed96fd3"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c6ea8433ca99b8a1104ee8ba3bb75d4677d71303d12515d4f0bad330c58cc696"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "9dee84cb2c362d1a7e84087cba331f86dd25c886"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "4e58ece69aa2a55196fee151f52cc9977f7ffa3f3bd7890a155f0a077529abd1"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "c0f6219276cd9fc51b5905dd058fda0a92100eaf"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "1ab900be253c57d29c993a5f1d58b53d3ff01e4c78102027aeb9343e6d3f9bcd"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "fc699c4a91df82e21065feaaed6b7a0a7593e369"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "68318e4715609f20230b13d7b9c2fe7f894e1290148a30477891a56599b2a774"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "5461ef309511476eb4810f4fa4593f74863a007c"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "9ecf697504729947e6e17fe60e88bac6849eaab4219a14f6928a73c59340c00c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "4b4f95d984b8ddbccfd6174a085e1ba3888394b1"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "0666ef459098c8d02c275a0bf62048c26ea246e2e5ee5d5c5b67d3f5304503a8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "8a344a7a1fd54cfcc44efa7cd0ae424cd388f849"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "b13cea99cd0554fd7acaa682584475860cb751ed20160d03f309a23b9ae385a6"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "ee2627bd0c4e20c4e899c709bf2ff57fd698eb73"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "a4b60b9512ec63fce7fab1d8a620728afc1e6a6f340c8aedab965098190475f3"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.4.0+2/SuiteSparse.v7.4.0.x86_64-w64-mingw32.tar.gz"
