[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "8d5f25662090846522854545cf9f562c0dd9cde7"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "46c38c97d4a208caed6a05661f55c9ef223750f72b71aac7a36853b302dadac8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "5b8d0ba3ce1a49b0cc7f3101b20253d1a1c0b35e"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "ef826b1834d75661c0c9b2e773509807ce03b88d3fd8ac5edad5e1378e653c80"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "30f260231d788a934fda29bb5f9bfbe2321ef7b7"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "21ed2684dc7942bc13ab1b1e075ba994542c0488d8a088392c0c30f03cddfdbd"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "68146c480471f7db57f2cb632215bb41eb094738"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "f500c616b18fcdf2a2075416fdd6234c3a3db815fbd6812c9ea5aa7126cf65a5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1eadf5637fd6c5aa3451633f161c6667c9ec951c"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "6649d41180913bd25646e9271a60c975246955e335d943f08d60efe40b19cca9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e0427e56a19b2d7f549368354b504af21d0bab90"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "66403903585805b4e4995c42213735dbbcbc1619905c592c62b98a6f072f2ea6"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "72923f57f3509dbc2e1b60145e032e42ce2c8c50"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "a3632b5c561599c08e2c1c81101991fe7b2f23f76059b36d687e61fd85f8a344"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "95f3091b67edd51c94190e9c692efd02cc881d13"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "44d5291f1ac14ccf964a6dadd4fb3ce88572912df32c9fca938e244cba18e55e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "3cfdbe7934d6465518dde6a78442456307349061"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c07d6b27ab0e5d7afccb4d87d772f55c253f1b62766b93197d9c65020cf2264b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "7664d3b9f724e0392b8e044f39e4cbb8767a2131"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "fcfd9605bfc960d765b46f9680299a2ea41bcf00ed5eb57896eb0568abac91ea"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "ee6ecdc3ca823ec96511b0fb5d140e738ed90287"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c4edd145fab4a85b16d514cf7dc0d3c62345fe090b5f297e9ed55375f0e7c039"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "21d97c57064d8e99e082ad9aa32868ce6744684f"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "3b9031fdc63a80995a20d634b893782536adfba3cc59030752d64673f02f4f9b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "109277892dfbd6b3bf7821fbac9bad6d95b5ed3a"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "a2c5c21a57a591e4c17e52467efe034a8464f8d2d5fc6c41f1b198079d84d262"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "50804e691cb01e986abef4143eeea4bacb7533af"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "5525a56665bf34f2ec676dc41a1764fa8e548e575d0c9eeb13c714ac5eb690f3"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "0c5637874d5f8af698ef4cca788f61163046ce73"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "42ad6a8ffcee5dd760f194379b03651aeaa3ec298f560db1b6017cd2581d7306"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "32d2c9788c396401fcf418b3fbd8ec6ff957c34b"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "a5f9cc0ecaf6c1bb974b670af75546b3c10af321b645b9b5f56c4417792695a8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+2/SuiteSparse.v5.8.1.x86_64-w64-mingw32.tar.gz"
