[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "991296a585b2e04ef48bce95a8db8dc9cc04f957"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "cf3df1d8c43bc354fd99077572f7761929bd4e424a70e380f1653f71ca1f5c33"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "f361ff0ef46ea010a46dbcf1513c12a1b01c3cf1"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "e0bfc470ee4aaaa3fdaede93a1a10a61342fed0a134959ecfbf3b2ad719f8bb0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "2fa28c5875246b5998429a007abb43cc41785452"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d4f1618388026c9d1cd8b1bd61e46a5a823c29b4cf0101ce825e452d2ffbf22c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d5dc93e8568115860d61be8db8689dd5f158c8ef"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "5556b90c4db65626b16bed9ab04656f4febee70557d36a0927d4ba4fac042390"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a99460375b56b9eaea2d6a486759dfeb836cbf40"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "50cb380922c71f6ac2bfb2a7c68c047df8b0d773b7cddda7da30870c2622e46f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "716875258860b92ed7c26eb577fb073e24bde456"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "0b8191e7089258ea19dbef38cd4e29d66965a6ef6ae8bbda40387d824b23d891"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "510222c6c0089e891c0697bf13c0dafc4f9d92d2"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d0b2d56ab6b38d8a7c8c1ed6de1faff64a96948db158807e59203f6f22d8b2e7"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "ff7ea3bb24099d5555e81c2ffcc9d183b43dc9ad"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "5ca69e0d5f2007101ee7168dba5cc6f8da9d1e4fadc86a42a65210a94de4cc12"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "389b7c7b0cb9ac11dfb269f830fab10ad1a6e9b2"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "94f79d23b3aba2761ecaa383f2faa8973d47ac71e387d06c2ff46c4650190fbe"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "0c232c1296eea1155672c451f24b7f35c42274b0"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "50d4c38714730ea4c48245441a7570d9dcecb85c15b017bd91c12453464f0c2c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "42e05190b0403ff63426f518c36d30c1e9253a12"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "82d0b3cc1c97e334cd6c4399d428635ffbc3955b877fce8da432128c09ea26e9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "2f5290f31104d4002e3e7a18b022f9aec6099695"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "b49f885aaec04d138fd2344bfd38a529cc274deaa032d7e7bf24561a120b56f8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "8dea51b11f1fe8990d89ab5699c566dcea32f3a6"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "6086b1c2d0202988909198f6ac8b36bfec28172aaa6c733baa013a0b83e38e74"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "c51abb0425e2d3090be5971ea20c5b5e7e0b20bf"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "f8619d843734125463066d431ce2ee25d78afeb4f93ecb1cb8f34aa09d7a6895"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "3d9530b5c086222a945ebe293e274c1595977f06"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "74a743a187da9bb829f51d31a84ac2b50dc54382c0876a8607548ab55b322594"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "a5a3b50485b0db999004ef8f0782d5fae02d2e33"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "be386c3af263ca10ab766f8ab018936a994bf2076e04285d904e4f0e35dc5e03"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+10/SuiteSparse.v5.4.0.x86_64-w64-mingw32.tar.gz"
