[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "f3c1c9c6974b54c3756b46767bc856406cb8aa98"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "9c830d0e0688f2550d1330637b72cc9bc0b57a09cd394132f0f6b4f97960bb6a"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "ff99860a7e66310f624cd8533fbaa6fdff258821"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "fd81ac8f9da7625caa2159b44aaa1e35981d6fe62c74c8fad97e92dd16eac0da"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "86227927c92d7ec1c8d5b40dcaf8906e52ce0a73"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "a39b7c30813d1767411f37e3e71e620c826512ae4c9361276e56ae5719baae03"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "b04477005b2f930178bf235d62b148f921b3678c"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "681aa570f4bf5b2a2c840b5cab1f3522f193e99ab5672ce1a86ac3540d9e6c10"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.aarch64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9f98efd138bb3a119a093a88d06f672e45f0bddc"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "0aa8fc4ccbd2526a355c5e4a8fc4f375045ba6639aba853aca8d0e59b52af52d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f4fd541b3d37b9c4f2ca758a87150c364ea34920"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d25e6817f3db5f57eaacc7f47325da191b7b72cd3aae7251eb42db04ed5c5d19"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "160c70b3012c4e208ba4cbf4ba7430c4529dcebe"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "e3300dcd6c02fdd751b33cf6d19876d87116b96aad0be809bdf3b51bf9c5adf8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0e4732568efd599969bc1a9c565271c1a4659c86"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "98b44bbc656e16daef78bd102b5fa6efdcf5804d75eb826921573cc15942b836"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "17eea29de8436f1a59f9c74625eff5ad13125072"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "60afa682d11e712a649647919b16725703bc98e7357b3827d1d339fceb122baf"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "4add0aece43a52c2442a94efc65f58090f11e0d7"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8e2000d06b2fef6a354644d68562913d553085833ec60ee560b38514ac023d3b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "415a30d51ad5a40fbd2aac4f65136a9899ca63da"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "2344aa6b4788e20e6c175314ef9304eb7314d781c114800551970a971f9c4bc2"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "502f7bf9a3faa3cee54821211fe6cd9bfaaf9cc4"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "aab8b958c37c472bdbd5da105d624cf4130e3846ce39b7fff3c4d374e4aaf1a2"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "445c26f032000173fc5a5b532766594c560041bd"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "83bbe691db1f70b6b07aa02cb699e04bdb2435108d6d10449164c6d19536f3ad"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "d63d1c4096abb379176d6cfec0c2c67221b79709"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "988b52409276a4b08332525c22382e352af53dfad84de0db33bbdff3ff412dd0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "ba2349ec85f4d6752852cc4bdd50e109ab42f5d1"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "5dc5cfa3c928713ac5a55b7d29a68e1b8dffa684fdc2a62f340a6f0128a568a5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "0d33ba6c3fae2484051d3fe0279e4f62e11cfcb3"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "1d3a813a859a585f2fc1813ed8cbd068dbb7a04d3237c83b7db639a2ba06936a"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "a381996f71c747aa1b49ca29a34a28f1e5e6dfb4"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "5d8c4b16dd0e7a07f5f5f3b457a665307a2de687c0bbcc7f194a89ef65f6a6b9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.8.3+0/SuiteSparse.v7.8.3.x86_64-w64-mingw32.tar.gz"
