[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "766c34b46232ef901d1eef120e88cc511b0ce40f"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "3a42605c7282929458ea0a7c6fc8564c3dea09f73f27ebcc069bc6a18ed3f6d1"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "122c769ccba166883bd861f58106772653492ec8"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "3ee0baa271d88a3d1cb6e10a56f106d5809c5984472bc42b42bbec9aa807187c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "b23fec7bec98b43d53063dc77a2532713abd18da"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "612ff5a768363ef53a0bb4188f25d17573cbaebc8f6084f4afbdb46cdecf008d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ab4a5bc77c4efb24761d53b1b876cff2f5927a44"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "3775712ba268c58b0fd778a0a96269ffc32dda519d08e05ddf9f8fb5db31bbb5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9217cd43295cb1937a75ab3a9d4bb95e00ef1308"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "2fc6098eb77f7fc147351b111c79c95a8aecb257e90b6f4e3db26022642cd516"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c2e5c9e10b628d29f8604c2a197c4c0f1c9e469c"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "aef0a9f21feb6dd5607aef9e58872f726fdfaef52cd2412af335aeb39c615a59"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "80809828c0ed6c143331082f5b6e297e85679254"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "2e734ef629d3c4a7f234f31cee109473176f63da7c27d5523cb5fed31b1885b2"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "a9a4ffb7609d6ba5246c54bab72d9720222170d4"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "272f4838cc0a52bdce93e4c7e6e589de7aca668b22fd3120e4fbfadb6677bb01"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "3b5f46713ec9a94f7b68742b422fa6f058a4a35b"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8f2fba0440eba0a925b09975f7060dac80c3d1006c22888d6893051fe5a7af43"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "3b10e1ec88aa01cd2e4794417b772a0b04971c10"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "811d977fe5264c82a28d69a12a454d08cd3e9a7e391a7a7c3eace3758a323f36"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "2b73c01140bbb1c8fb4b2b0db12a2ae4d9f7aa3d"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "45a8c3edd5464bef011f6bf637ed60ca4774f6b572a4c483bb6d791a76b0326c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "5263d2580af8ea799df216eb8f4c42b125045568"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "3d062f858fdbe559af795f8647cc6541bf108017457aca1dcce77aa1ae9414e5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "7140faf50a6c737f5a42b566298ef3c653f5c555"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "3d429d56dd0331a05318618fd98581be127bc3ff5f978f54bf7a5cb9221a885b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "f1026824b24546e2a7cc85a200e8b60b423d1ce0"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "f331bb30658a79fbd923db21c52f1cd6c4449787bb5064c5b90b15ba5ba5d57c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "c00760cb6700af0848cbe2d0790480b74da6c21a"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "5d2f5d6ae3a6dc3e01310cd4277919947af903cbc2bd8e0ca7a1fe32562445b1"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "9c0088f3f3ec0e27bc38ded5fde71d238e71ff3e"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "3f25fca9efc68a22c2a3bccba8d2847273989a67f87a9ac57019ffa3c1e9c058"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+3/SuiteSparse.v5.4.1.x86_64-w64-mingw32.tar.gz"
