[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "1884f48ee47c692a07e9a6c724f83f697dfca389"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "4e58e8eb9bf29261ff96cdebda0dbdceeba0a24b08ce3a8d1499874cf94a57ad"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "68d579b4b8c6f950cf15b513afd8ea94d1baa49d"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "84fbeecbe8388a27c9ecbbed01682cc3f5716e9fbae55a2f27867923ad60da49"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "b540e34ce90ac603f7eed5bb8ecb924f0fe7bbaa"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "e4eb66b810ac95f91348248f32eaccc759d9d89b0cf9045c4d81fc631e3cde52"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1a663fc0d97b75326de7a3e51bd178b9f7b406ca"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8f94843ef316900104a51b59dcd1e7717df2f864e0155e62f73a9738f24b8e37"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2a81fdbbf79b246fcc79dc1eed89bebda86d3636"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "48891fef79183a01c3394c321fdcfb69932ed22bc63a901dc1e003eed2b020d4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c07b5c4af1e41333a303027e97e45ce197eaa52c"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d0272843e13fdc9f1c7f19e2ddb170bafe73046b7bc26aefcd2bff09b1dc601e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d39faae7e91e80f8bb1f58ab2cb702766b74184a"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "f77e7ac068c41e6e8464ab05ec57aa6f80e7f1850352be30beaa6a71a59283d4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "edf9ff7b90ab46f1b651816331aeba8ba3f598c4"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "5e39cc2ea536f8e19ddc33fa317f7a3d417b27f0e7c0d919dd5d4079400c71bc"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "a9c2881a7d658abc25902dd1a846b509b3ff7d19"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "250c286036e06913d7385cf7b2e83fd4af3203924ddf2a394ae444a3cdff542d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "1a6fadf7e1cc5f9bd5cc75f78bfcab02f5ce81dc"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "5d5c572e3f00de180c86d4174e1eb223c64e5691f71003f51e785f10dd5dc729"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "78b61a2f029dc0adb2af07d5b6551e7ec9e58921"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "50b184444a212e15a94f4aef615893e620bbb578a5c143a5d0a0ac08fd169a07"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "24800153fab26f85ee2c40bb27f26206c07c6dc0"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "e2bd28c119c66d9a5776bed8b14451ef90293005537bf8fa73141376e3b81a59"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "81d7a36ab9eed522746ba96c9eacc71babffe645"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "ab4c5c2732ec0d6fbba54083fe5d8850564f03cf4e9f6df0889357cfa8b32e86"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "6c97db27edeced770c549ca0ee179fb1b995c052"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "557c2653810f350c6c2879e6bf6002fd8a41ad20379d5a71a3617b7519ed869b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "fef672c4d53280631e1945f9ce147f6b53bf60bc"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "7a98e070c7642d4a39e95a746621d0e0bc197d2eec6799bc8d26f8697daf8dc9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "16421886e93545045fc541e0db684241f0c0bc11"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "e23362adadf5756bae33fde3e4c981b775d9a5791ca975c98f01c4e72fdada27"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.7.0+0/SuiteSparse.v7.7.0.x86_64-w64-mingw32.tar.gz"
