[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "cc23369b500e0a3769ac0ff977402f7ade09c369"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "d0efaf630df73c404ae79abc590747a3ee353614929f8193dea007a0334cc48e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "9e6281b64f7713f5d457e597ff61f1f43e6e9ca0"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "dc97809d399445865aee2d6422e3a1f2a73b847ee586c39544af684dec1b8c46"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "7056a7764066fee60197c25b71ac6c9d45ccb982"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "4b61b3d79a3913034d34439fa3ec77ff2868c71540c894621d66592c27015ebb"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "305fda653912b74e48a2df427024f82dcf24fceb"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "49219f9c38a9d08c346d6f40c356db03beeb5d22481bd450a6910e449555d165"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ecd981b0182e80d9474e72323b1861803c7ca72f"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "a36b5efadf50774e4746530ee24bf6a6c14f98749f3ed6099685e2ae553436d7"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f69d033d6afe61d5afc2945a5f1483be12f5eb57"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "cb0ed9e0087c6c196bff9234e3ac8599f4ff880fa28b3a2c29c124027104cc92"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "00f4a753e93cced5f47e91ae990109b42e5e17c5"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "20d6e576ecb1d852db866f14b312cd7753e30c458a0303b4aed15fcf218ef5d6"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "666a9779e05c40f0dbdbb5caa5484cad45f2ac03"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "fe49bd50e783c21e92a615d3171b418f64ef2cc1b5cf177ccaf2e2413eab99c4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "ac9beec4d346d8105f3310797be5a8e02124921f"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "88471414aa2777704bee737d4355be577a5ad1ededade76f4650b5ee44b45b2c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "48c9e89b61f54e0ef878aa8378fbb2bafb0a4b3e"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "bc999c156f168a18183ab3e2e1b356a1046c8986d2afc83ce2bd106862c0ae56"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "f780e98fc722492ed8b02165e00dbe60f8e1a538"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "7f6932dbc87c13df5bdab86780575955204ef582cec70ebf742dc6d51a095652"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "7062caedec718d125d4688df07ab138d481d9a3c"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "90c584ec5684ecf86e4e275b0ef166524121faf167cd893b6b6cb86e71c86c69"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "46179eb92ffd376166e3837d1807d7ebb434582b"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "45868f18d4c003b1ca5c201ac42217e32b0768ab791de52b9f86977edb836acd"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "ad2c8a04945b6aa67505aa798e8a49cafc26f0cd"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "153462d5fd539ed6416c95cfcdfd9f1bc23dc085de888a000285c58bedfd6c63"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "ee882073c52e8b48b1abce9480630afd21854e64"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "23b856aaae43c50e06300fc7293be4761934045e22528c5cd54912f84a128f1f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "22b6c5571d81302ff32fa44d335d0699132e526d"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "462822a0c9889010f301a5d78c9da9d93ac9b225dcc08b5a05549d78c1f5baff"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.8.1+0/SuiteSparse.v5.8.1.x86_64-w64-mingw32.tar.gz"
