[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "ad17793160ab389ad63571139384313305deda86"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "08bfaca19efc110bc419c8e3775a057f2283b20a80fa157bb7282ee7a4d77815"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "fc119f45c5579ca56fe4ac9aba82b1ca476effd2"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "5f0d001910125b4d935ebb8bd6d0c5c65231b2fe023ab02bad3c57d9bf502ead"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "907dacfeed849476b2e418f5ecfe879426512e66"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "b078adba3930b5f26e9f2207b772498d7bb8846140bea2c04d5c9cc64f1bb7f7"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2d6e9465a902e6beffff4ea4b2457417f4da12a4"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "abd852aa6458447ac5697b6726354fcb04a394c8b58bc2bb7edeafdd5faf63a6"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a31326d1533769400cef59aa081cde5a2c44e4bd"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "30ed704f8c970ed5881b715824d82818c43f2f7962631eb2e0f3607b6f27d38b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "384e7bc7ab3b20189dab6cf3ba97df0198b2a580"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "a4ce740829fcc18899a48484bc0f14fdd2d45e53ff560bcf916a9e5c3edd78ab"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3fb94249ca1c996021b375b7b7d8e87e1d157ab2"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "f3a4803033f1ed0daf3e5c56870c11fc081831d143f9b5e25954590fde1b9081"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "bf9c898c10d4fc2036fc4f258fe6e2852a2f563e"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "0f4a8e6181fc125c57733f3bf62de932e3a5b4bb8130a8959483168c5245ef6f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "e48554b69f225606e9835928331a1fdbaaafce57"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d37a74f370c9afc5362e9e986fdcae26a0428a87f34859fd6664a756472e5616"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "cb76cb871b82489621caded73443b12b5de9d197"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "114453d86724931fcbbe4493e899f5061a823edb62361352ab1e64ba6c45143a"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "f411357f78d70b4a782590983f136fcb1d461754"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c13365f8976fa5e2efa628e60875ca451d7158f39392f315b124e4b7ee3aa311"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "42cac79969f66588a680506494ad4447ac982336"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "8c5a56414e8349015238829a32c1e48ed0f4ebe37f078f8c1ebcf984de26f26c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "7c2ca7425f560ab5c86167080eeccbe53f2d999d"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "aabe58b7b3de69a71ce9ff2a90b71a868a4a7c75f43f9912a440b8e1c6b624fa"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "397d311d1c386662765c309c2e656ac170c92cc5"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "baa07382b1e30c32fd2b53700bc5149463e80064ae16085d7819d9d52c4a85c6"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "946e7b503e9ac715de2b047750e0c96e14c597ed"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "2c3af123d7480180cdbbbbc412308ddc8f5d91464b44da19904df7cd3f9905d9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "62aadaa4b5b614767644515c07fc175723a7ea2e"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "38255f811d34d72884e0e100d416ac89eea55515d4c76e78de23d2b5842412ee"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.3.0+0/SuiteSparse.v7.3.0.x86_64-w64-mingw32.tar.gz"
