[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "186bf3ad14ac478f0e607677bf6cd526c070f4f2"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "ca94cde500f4bc4d127b753eddb6c1a2d43d2cd30e4a426e966a4392e27b91b7"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.arm-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "7846b0ccfbb644d286ffb0344b6d924aa042d98d"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "b5dd7a3dbd9f1de6b31d00915c170766d3f28f929a31def98b397391fe6aab6f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "782ea1e43f6062e2fe625a8f4f139bc472fd2bae"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "a554fd960fc51646a5fdee25d2cde7c24f13a247fff0bee23e48efed9d870e61"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "1ca628f19425044b7dfc0c8cec974da68f8b1578"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "7df4d0de0e6d1de4031850c41c9be7da1906952babb8e7be10537407581ea3fb"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "d4930e6b2d3e59dd073d80de589f5f2fe0971547"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "9afe984eb69f3c8c1feeb1b062ea5562baef31c741e088bacd6f70f925ef877d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-apple-darwin14.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "2277cfd61b7eaf14b6d04157ed7dea7ed94c1e86"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "e31069f5863df3264a547cde0f5edca293336426dd5923cba2afbe0560f21532"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "9aafb8d5e182c1ffcb6a9a902ed587ec1251ff10"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "171e0430d643819f64bc557f1cdc15c4e043918c582e3fe188e67d06a6eb107a"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "9966bfe80bac43fe324c54313ad3a8cce3f93a34"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c4ed50c1cc335f614eb1e57ca4a36f399cb37f8e90c948ca7c46bdc29a2a7032"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "1e29479eb653ab21e494466bf86f8a5cb64263eb"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8d49d2e22869b7f5541257c81e85d4b18bfb03fa546d905c9063f720aa7f4ee9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "108b6d413bdc42ed551f986508fb788a17ce3458"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "164cd9756ff8c0fa30bd95423623fd7ae59038ea846439bad4e1c31e8d061e05"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "604d040e05dda403ec1cc2672a982d2855fa98f5"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "57a00d0d584d2847d23d1db8e5435ece77830a232a206ad2e97bae3b999085c7"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-unknown-freebsd11.1.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "958d2d985cc2b51b4a83387a7bb08bbb228cfd4c"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "10fa94e18f5ccd014412d79d906a0d36ea93fac0c8a5befab1183e49f33ca945"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "fb28260fbceea0a904f0603ecaa8db425e327f12"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "31da71f316d5197a1337e1e18c261ddfa262d978fc97a01e3131bca101c5cdda"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.arm-linux-musleabihf.tar.gz"
