[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "0fae18fa80161e4d5fe9137747ca4f0f1dec96b9"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "b8f8e8ebb2aa57bd664205c74a16a21f7519ac5f028ceab9aed7cb618b08bc34"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+0/SuiteSparse.v5.4.0.arm-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "ddfd6298ec04ed9f10a46a693c4e2c6fbafa6b79"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "b6ff1a16bed015593388cb35c46793e0c0f32631172a6f633a993f9e6d95bb59"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+0/SuiteSparse.v5.4.0.aarch64-linux-musl.tar.gz"
