[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "c1fd84dfcf4c9948dd56f129f687e681052d24a7"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "5a8c0e61852529ec3377191e0b914086d96aeb22fcf526b6eaff2151f16e3c7f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "3fc00854a8a8a43c04ddb356b88cf182c1bd201e"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "5be870bd8fc366ab88793b1ca6ff14848363f6fa4c2ab8363289b9ccb55d864d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "9c6bc797cfc14abe954f1368ae468c3470fae52e"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "f89faf8160bff4942c08c9daff343c47ce34e2498f0f0976b661ce700f79efe4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c21d65b4a3e7b7632e7810a468de5f9e5d9e711a"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "bd37df817cd37130f0839629a98802036fc2e7f484cad9eca87cc5fce550fc06"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bd44d37cf52e9f882f9c9894d0135e6e4e601e93"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c7907805db97eedbe9c186bb72db88d2fd8b2b5b9d214a5e294a7e3f8046156e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8ea59c53543671526e3631df3832717727b8fe6c"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "bbe2c0a72d205e4b196b9cbb32288ce984d8fa82ad7d522b82d434f52bfc0ee7"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7d4d7b5b969eca02bbee37046eef98ba4cad134b"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "e34a821af3173193a7ce514a1d17e62ecdbaf65223df29b2a36e323b10f24a03"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "1425a5360aff728c477737bb5735403ff1992e9c"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d81d17e8d22d061638af63db3fed37bd81c53c6768596112e0d1553501418e9b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "fabb5d01df91242af096d59206808ca430648d6b"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "998ab8c4363737c41de056a613ca713886813f6c297766e7530f1bb20f81bf8d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "35b5f4bd61c6c0ff15c07d8b2ebd821dcddab275"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "4b13dc681c156a97734cf13773b3502e2bad41560bb8f0d21446980e48f649d6"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "85d11b754c35b1154bd65fe4d114059d1196ab8a"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "6fbaedb730bdb157f6efbec8f94fc3dc8cdef9fcded01a6cc7561c5d7164cd48"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "abb1c24839b75c33f86cf97576bb1196a6aacbbf"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "2c89f22e298682b8050c087909a7c46c69c257518f2a31966cab4e1617a1d374"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "417f3aedf4e87533e37b13554add8b4aee3a9b30"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c0c9c12a4eb977a42bf0e60ac3f61fce6095e6f757d0be186474c32f813d19e7"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "6cdab4a19ca46234176a37c3d9293ab8ce20cfdd"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c49d9fe4264c720e52cc2e499b44f14dfbd968fc6fdde7a6aa3edc093128a058"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "c20f02efe0bb0a05c1d17ff9857af5af7419b35d"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "be3873e221d00d15b0c991ae9166ea14a0919d54d225e86e561e9168f06371c8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "262c55494452b9c5d77b3b4f3db542b6781986c1"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "bece4f598c061b8f4246fc89b582898b893859eb837b2187cdda9db214274c7b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+3/SuiteSparse.v5.10.1.x86_64-w64-mingw32.tar.gz"
