[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "4a1351c3f097dd250cb8af43e7ff3405bb0d8590"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "1a4188cb798c61c48ef2599f154647d3945a3318b91e7f971bd4cb5ce652b35e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "0048f6ddbe74f1d97022b21e6b0ab69e89d5655e"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "af979eb3275507668f9568bd6f6a7263a0083b017e2966475699a7725da9826c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "da31f2811877f134053053cb6644e94e3c75f759"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "bf2810499b3ae94a34b05a56087f2208756ddf8eb4213c90f49a0cf7696b64a6"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2d502904a530e8a09930c00cecde09910b5c56b3"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "11583215d4e47276d08f3e2c409e82548a5583c9b62b1648593f7ffe37693da9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1987abcbdc96c37143b038e97913c6ef166803b0"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "a0a841753268e62bbff1c4e4a7c505d218057e7bfb9e8d0fbb5000c5df8c0a8e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fb8b266643c9e8d7329161680e842b245527bea2"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "87700dfd5e0b978ba914f85a91d0ded71549af9359027b8ef04c7636d4584b44"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cf8faef08e827913b6032b5707d70213ce4368ba"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8e4a465eaaa50422e0c88fd7c617bb04e7029449786d7b4b353fb4a3987e6525"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "feb6f74d492d62d7c6cefb9ccb525342f99b6533"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d626c06d3c8fb29d3ae43b4e33c96d1ef10daa8c2d56a8050675761509df8f0f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "d43a6338d3eec309cb59f8eebfca3897e747d487"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "4a9f2bf4818018e4df00eca6463b3a34b5445b51057dfda771c58f3b6ef49656"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "802b00ad83d4e14f4e1931dc9f574eb4600d397f"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "165c1be9c3ef1a964557e399b834ed74786db5f2bb75ae6bc4beee50cb8729f5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "904de17b2647f8788957c23c552c87e19ba4decd"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "057167e0a284246c9de6ac35ed911765736ba3729176270a425afd4f860bc157"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "ec927ea8ad3708b669ddb61542380c18c1e75dc5"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "07cade1d60a3badf59a577b09f194495f7378414d4045b5ee407f1aa38ad465d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "f79a14f50e0ca596d31f8ffefb11d3463bd48318"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "3c2574f46518ff07a8bda63d4ca6abd5ff33b9127f07497540df56c987f3f9af"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "f0e98a8a6587d60c326948f88f57d32838f9870e"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "ab74d33a0afa3ee4eb328713e6690a2168877a175817a35186c383d8dc4bccd9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "d6a06ad7f20545bd55cd65321400ca2b5172a1a0"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "d32dcb19c3d63298e2dbda6aa1a5376e53c12a468cf88d9a997f60eab347e0c6"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "1235d4706340c703057a7455e690ba1306b71668"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "85f4857b3270fb569f74da177cb4f3c03e4e87fa37ec89627b1e3f8e32a4000e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+1/SuiteSparse.v5.4.1.x86_64-w64-mingw32.tar.gz"
