[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "3bf52fbd16cc6d7968311f51b1c3468b72e82928"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "b546414c8629ac96fcd6695f50a808ce4c8671fbd61716c526cc6aa26af2994c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "aa33d36f4b7321dc97b63d6b9ab1697a28104faa"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "f5e89658a1975686c366521037de1e08a7f71c0e7dbf5d63a74db3502131cca2"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "652d8eda5fd18017333ece265358ad63db311b37"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "7ef385077f51960b8395f4c001d63b7e38e39b7172ad316b65d059bc55a2b4ab"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d53c84f757337ce1787c82ac4a76cf03246bd372"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "526369b2b38bf2a6fd32bad886833247ff64640d6a60fa75f63a9893ea276ecc"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9c80639bdb399a7923eb85716e5aa4c1e5e0df59"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "084320f20f0f622347301ee71bd6ff81d9ceeda001da06b0ed8a96abd959ba5f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8e7d5a17989489522c7089c16f101c7b625402a9"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "66b48e4cadbc3af97a7a3c49ba85299719723825917bf04e933e19b9d4280782"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6bd386acee152f113e2843e3647b9c5cf8a6cdc1"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "07ae8f033efbd45c050215fb0e30178d221ab3ab1f6841b675854b9f6e5ad1ea"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "4e15a7e0d48fba9b86f3ddedb790bbd3f5195aee"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d2823c68eec07066d2c83aab0b321f0a8761acd52f960e8aaac7d28960fb81d4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "087214e718938b932b26e714f83caa7d93c50c5a"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "9d543a0b6de663d0eb925d62e0312babce93996201b4e0f976f34d2e9b1a6f4f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "12310e24d9beded801754372476e8cc3cd011405"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "f953e4455b118f6b0813badb1dd24d22479bdf344dd52aedfc6c027d27ed5ad1"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "3c29792e93c668199dc7e06ec5e65c467498e522"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "1f6f81b6115b8d9eb867254f0f4402bbee95016134a6d0a1156e1399746083a6"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "91ed3f77b78a7113f38c5baf9eb5dac8510bc0c4"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "7649a577cdb1c453e69ae20af56ddb591fb26331886b77073894ac60e63ac1d0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "251ed8af42d30dc92a08ab51a6f02374e8c9b80d"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "53ffe08127e010d4abf717f6871d9cc8d583b426e514309e9f0a1caffddbbb92"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "d2bf53c23b8576ef40811c566c96fbc4beb056af"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "800a2c6087282ae9cafe1838fe52dda6c00f27c2b193e5260deedeafbf41fe78"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "12f01f0617c36d696423a23a4a5bdd05379ce654"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "0699ed177ba63515c9e8c27f4f9fa05da1d39610df3513bea26ee22a3af5ff0e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "681f7a2f3efaafa785217ec54012ac007a53ca6f"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "643f608b202ad8ce2eb727155fadcad839d36277a6a64c5481501223dc44dea1"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+2/SuiteSparse.v5.10.1.x86_64-w64-mingw32.tar.gz"
