[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "88d57a5cf9b0ff1bb997dede78c2db0c52e77d74"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "4f55770b58057778b69e6d1b2830e4201019e92c1382134bfb7c010818d54126"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "0e2a55160a6d93263ef337e578c63588fa2f7566"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "76fbdf01fbd9ab971100c48c082488ef16542174c5f33cd82b21c6e841645cc6"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "494e931aa03c5d6ddac8074b385109dcc6c2232f"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "fef8af95b900e374268e7a10711d331048b6ae74466b938f688d19d500e49df0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d03ad6b9ac3a764a6409d5f1ab868047d1a46228"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "5aebedbd5f0760790d3787b800c7e946eab448f8262a1f92cb5b2ec7b3e5da61"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "17c19234b2f551e2df71648b41668c359e01f5d3"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "993498924032110b2d1b8691972b3f682a657986bb5cbb8ed9bddc9f9f464080"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a0c0f8433d9151db790327981c7d963eb2eb1bd9"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "63656ee99034d655b50d6b579fa229cd2b61bfba6fe917f39b34d03f9aa0a361"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "29ac7554f64d184a2160b5abc621f009d754ea02"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "18b6df0e2a14e1e354043c225e09dff7b91f30466c05eb9e087c7ecb53f71db9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "c27618d70871b6180e90f46eb4cc93e4f4f33d8d"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "64d4e30c42a5633ae0adbb6e44a5e749ccd385dd6d70224c2edf60c77aea43e8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "6d71f250423e5c1364f6b974bd10b4c119954a06"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d013c8358653523a33cc6f603f4f4f41cf9e993210d9c6274133645ad7f42abe"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "4a000229ad0a5312d54c4f25fc8d339b6eede2a9"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "624d1d609cb504f0f649b778522401b05a7582f58ea061c0acb8200d21434ce0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "ee539232ad82c1353eeb0594194735f36965fbf5"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "620444480a80161a57e5547a266b95542cea130e59d56746efbf6b3d88499b8c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "ebf2b431a430c4cbdea7906df3bc0a6a4f57191f"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "efe335ecb08cd21ed2966b2246b8e639545d6de85e9952ca61ff0263db45ca5e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "214f73eb5b4722c8ff43f89bc9ff85206fddbac5"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c7c52b7645b63571da0717437ea137d48606eb75a821527709dc4c32f6bf785b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "44c4cdc80bb86157bc0b57a49a6b6934d5d342fd"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "5c06fa9cc4222fb39eba3712b0d834efcb71b6d03e963397f196a205f3008749"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "a04b83bbb38211ee8d631b2cb94e17a049f71642"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "fb9d53778d4b8c590c2839f2075bbf7ccc0ce3db16f068886a9c5ec537f6b62d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "495797c1e6f4c0f12298787d6e7d137aa45cb1ff"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "51183a751ed808f8efaf4aba6969440af33cdbb954e35e9ec111016646591dec"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.0+0/SuiteSparse.v7.6.0.x86_64-w64-mingw32.tar.gz"
