[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "3060af07300d8178c8ffe15c2513b9e7fc270638"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "8e1f68b7c7b4245fb197e1fb625f504c2c4b530bccc10da6d839283cf2f2eb6b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "7ef47625922bf52a3974c645c43015987f9906c3"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d137f80fdb7e7748760a5fb7b2b09847728dd73c42dfcba0c03731bb643d226a"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "7901fb49a003b17eb3a398ba855d312242ebc91c"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "185881d842826bcd27a00027c9f603037698a259763c955e549ed2b0c5bbc464"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a947b71874722b13b0e71d238aa3c62508c0dc55"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "502fcd1b22952bba595d13c852eefefa2e28682dde24a6715076a5b66951ffec"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7267c511b49f3a012a7a152605daa787d031d662"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "21b7ae885e15c5f79c6d41dbacbc9663ed904f45e3435f54a4e89cd1fa6d02b8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "295950876a59b955b0dd497271c965f4729271f7"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "eb59ccd9f9aa1e396500bfc1e66583f9a5a36da07101b72170921519da063c1d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "65475555ab0c5d3ba509735ff5027a54e87f6802"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "14763b130dee82410ed6b2b6f1d8c91517b359bbe678be06ae4ba389131fb026"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "7cbf4ad605227586b02a0d724e73dd4522b370e8"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "531866ec587a8f02a2f25a424c96916a5edb755037bf578c9ac4f714cdfaa912"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "c09565ada07e1c8a8d4a1a1e911fb8dbf1ec4097"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d6b3048a637856af9ce20d948335a10ded912f1e28a810056ac1423644dbdbc1"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "c285ca953414f73a6672bbfed63b55f079bf0dc4"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "d0a5cf65445dbe8039e1fe0fd8e03cc0eb301795abfdd6736eadfa976bf84bad"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "32ef3deeea07dfc09665cbf2e37af9872121c548"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "365401e609d4d1354ca368888965ec2e52229b889c41b7950983ffb5049a0761"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "43addb38736b907c8a107aa23d78cde767e4eaac"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "5339b101e80b61e107b8debfbb25f35bb0c3d698ecdcd3619eef1abd1ce23930"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "e3885c829c651b7e4602b5445bd1ae77bdbd3369"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c5811b27c62cd06d92f4c1ad9dbf1a99a98dbe3e7436f42d854c877f489147bb"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "6bcb9a41c6bd074863e9c45e10a796dcf431e812"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "bce54ffc1ea7704e826e7729c013dc5ff857ecb411e6d29591d7f7c979fb88f6"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "01adc3003098540e4fad8e6e59fe92260a34de25"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "72924be2c2f6088a4914c6fb8f4fb88475d2efa0dc444fa9b44488dddb6f2e3d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "60e9c390bc22cbbcb7e03c71208915a62284a661"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "731e91ff9e02dd4e7390e90d4f4818f102f3a324a81131572278a57534f44db9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.6.1+0/SuiteSparse.v7.6.1.x86_64-w64-mingw32.tar.gz"
