[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "580ef39b8f9c6e5440d84791df42c4650f391e33"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "5f18e34c1ca9c4017aab436584ec6dfaeacdcf99a66afc2a1559a2ab0a7af339"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.arm-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "d4bac45f9b30941768873e82d15d99993348259c"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "00544608364f0ec7f7fae4cbe6888ca01c5283ba5a5dbebdccabd68497971cbb"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "c7bd6732716cb280a33211f56ae97839b987ae9b"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "42da3f8987c0e78cb29ebd6c6a5120eabec2d008b24eb416704301070f69e263"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "475e086cee53e33752888373ac8e425c9acedfad"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "7251844b8affa375bd8662a29c4ff86f336a084796f60c34ca1d80ab9bd6ea44"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "e7db1f8dee820f8cc7701211f5cb5e9c13bc82bc"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "5bea96808f17664e1609d4abddb250595b949c0d88ca5369a6ced25189c5a797"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-apple-darwin14.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "1aa58f8332d2928fada5fe5b135f47f1cfeedb5c"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "ef93ba2f3130530ae8ac0228405171c2077c6a446c29120166f6d40c7cf23314"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "f4353cb350eceeecaa88b8335da594451fcf8262"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "333806a27cfb37f4542bce42a21c142374434718615fe68fca8c79713cb3f4e8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "3ea804f3152eb85ef1c165766591a95e67587d28"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "bc398fd6daf0aaf02bfa33f85c8dcf63151af2d3b4ad01d342b3eb4eff347cd4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "57899db5cdd75aeb64924bffb34ad1aed66adb72"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "e328a29ffe29c83be9062e972dde92189ae784c068fbe014f1dfe2327aa03038"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "a8795edabb9940669769c79917b8af9fd087e25d"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "a2d9ca621135a568b1461837cc5d13bbbeac3d7146602bff6ef76100c1ae1a84"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "b332547bfc2401b86820939a840a7077dc7abb06"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "f2d9a21830d3ca20c0cf74a4836f351188e653e5f3c41e5c43c180824def8dc4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-unknown-freebsd11.1.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "4335dc85d3e75248375cfcefb3916a1a5bd523fb"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "84c81cf9c257848af116e705cd6a0759ca776f40519a28197747c01164044f82"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "c602f49d127f34e4a6c0a752754b45b9c85dd384"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "2c15d510a28cf6426c6316f07ad5e44b2a9f9684de3ca8b2da021a914225ff68"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.arm-linux-musleabihf.tar.gz"
