[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "5e468b30a5bf2824ad1448c841654b00a67f74f5"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "3dba001f10069eb92edf3c50b0e45229362b310a38157b36828da3229164fc5d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "72741d214f2a2c0a68466648afb8ca197043157b"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "b2cc3f3c64bd227213b9c58e4e84194199e9f4b6f5cbea0d5126b175a1fe4353"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "c852f1451ecbb2e3a510f341bd48511783bc3579"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "f1bec83ce88a4a1303c58d7535964f7634499b86631bec2fb5245182841cf84f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bc37c3da4b8e12c87943e494512645ef2857e36b"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "ba71e391e191b2abafdc7184b4bb35aa6375b1bf4f1a906dfaec343e531a58d8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6f17d1ad4b9f89f4b1d0e277d711c2eeff7fdc7e"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "3ae12968fc12b010316b6ae4d5b92a0c8b695c52a892c20405b64c92f74d1d4f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8ce7c52b862a29babb7a0632d69c40cd36c23c4b"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "fd2b47fcbdecb0cb9e372e03f8e648ea4533da6e2cecdc98aa3d1375a10b5565"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ae03f1af851362346852ca4c3cfef0e69c3d2aa"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "b272207c70b55040f84371b681d954558622c8377d96083f5ef51eeff337ce61"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "de005a3ae77926d17bd03e8592664effcf8b1531"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "3f49c63a14f829c779f12f2d26ca0fdb1f1bf5eef53f261c254afedfb85e0f4f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "89ef0b10c0b75746b7a1548dce2d222a0ba08de4"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "0608ed3ebaa068a8a1da30abd9ada3de0e103fc616ff2a7b60c7c53ec05866be"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "dd0f767d9366bec82d0918aa7be79658430e3f8c"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "fc1b70ab6569ed9bd0bef8edce4ff76bb4475409aaad3023cd1403a2fb65892f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "1ee7c6321f9a80eafc1188e93bc85ef05aefbace"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "9c28dce9a9c2a820613ac014ae380648a75f6e251ccf2628e3677a6a97768188"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "e7d0b91affa3d2eba54ffcb65b229444ec190329"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "16e2ce1a1e538aa6628ac887f81304b27484f51471c0831f6fef231b7aeb246c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "46e00fc0b8bf28e6702ce00dfa5d65a5c7cf0a77"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "1d8f0c89f51a1f84ff991942035d63f1b08271f54ced5ad5b77a24409a5bdd35"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "a742663f8678947ef7c21f69acbfe7c7b4e4a68f"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "76e5d69876279d782541b07e7183a32c391f0aaf58cec50ca6dad1f47af0f6fb"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "609035d004f62386d9ba06e3541bb5b6a29dcd27"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "7db10c2ca980039be783f4b800e7206737e017f3e8055119e0fa23ec2ec55fef"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "6f138298d2caa5b5b6afbefca3782e45287210c7"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "cbb046bb188a16d060f39632127cf4cb504f8937671542a3fa13191044bd528b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.1+0/SuiteSparse.v5.4.1.x86_64-w64-mingw32.tar.gz"
