[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "96a6aaf1d284950795c596abccce2932512743cb"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "0740bf2347de4625e16ac547dd1ba87e6d7e2c00750af2eb5f5a98280d4ec879"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+1/SuiteSparse.v5.4.0.arm-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "7cb41d6b45fe5a374ae9a38fb42f6db13e06a6ab"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "ce71831ceb6b1f9cb938b90ab5074f9c3173b25d109429a9efced4af19295caa"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+1/SuiteSparse.v5.4.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "1a1c5b9702ac6445d0f82b7e1ac5799a7289393a"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "2563c4124a5cc37d0cf4975281c44767f957c37dc3252031f5e63288a62b75ef"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+1/SuiteSparse.v5.4.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "edf15adc7f1260f3046c779edef8691118b3495a"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "cce79b7bc176877af2bd069d25eebcb2241d6ce16c56a6d0888e64ea0beacf79"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+1/SuiteSparse.v5.4.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "485712cdb172fe214581028a598154ab93578e3f"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "2de2037b64e13d3b5f3d43cecc902eba7d85d3f4baf9f249ae1b3e55c1efd973"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+1/SuiteSparse.v5.4.0.x86_64-apple-darwin14.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "5d2625bc2eaa9e24b23dbff3b1368e496a20eba9"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8e86a62439c822074c9854647ec601998f320533c6b0dac3dbdfc244f6d2ba58"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+1/SuiteSparse.v5.4.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "8cce280a2a0598dfdd53f81a1a18bab4dd7d041c"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "7a8492b572640bd71e5a18b915339389e2acc4b7151582ad1a5be8242f431d6a"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+1/SuiteSparse.v5.4.0.x86_64-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "dea5c991d7a5b340712d69850f593be8064fcf69"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "f37b41cbf8c6b246fe1e96ff1c6430be8bf9abed1af8e13e97805edc8bc25071"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+1/SuiteSparse.v5.4.0.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "5412a0dc6d3720ded638164479dea96c7b43937d"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "36214ab7e5782f1b0b77172ecc29ce4de864fec06a6937c9d351aa6d2a349f0a"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+1/SuiteSparse.v5.4.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "57a71dcd031ff63a83bac27a7ecb03119232c6dd"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d07ae9d9bd568378b08d8d36faaa7f81ee4d074a26b6697f84ce956dbf331444"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+1/SuiteSparse.v5.4.0.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "c0fa4f4e676ea6dcd7a02513bc44d1f751495faa"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "297d83574c3e389f9e162afc830edd20683c318306bac7fc4c2c034296acb0cb"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+1/SuiteSparse.v5.4.0.x86_64-unknown-freebsd11.1.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "1d284a0e98cd9b58229e14c5ff406a8bf2556b9a"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "6e07dd00da1abb6880000e51e74cb17f356b71e650dd160b2cc7c918e217d9b7"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+1/SuiteSparse.v5.4.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "9ef8913b571208b758b8820106b91358e7a86eb5"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d1bad40d6cf91ffd991fc99a9882921c37775c0f95acf2ca08b410077ba06e9c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+1/SuiteSparse.v5.4.0.arm-linux-musleabihf.tar.gz"
