[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "c650bb6223f97a766f7f0c71eef60e660c3bc2e1"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "4e80786818f58999f88721f79e6ad8a5eac6ec5f74f4f2ca6c9894becd78bc2e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "6f17d66c672877fde2a4090c8066a1c44343448f"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "dec97ec57f6e1575795c4310aee71635fc51f99069910ba4ab795188f6e5bcd5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "b47f70d736b7b56467a2ba507e3f351ee70d27a7"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d870142796128e8d79bdadcb08631de4ea4bcbd824ecf6197a52a767aa79470b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "510f60ada2a81bd46b79b5be274b6148935f6a5c"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "699883306c8136c2527eee2bd31f926c99072a02d88d3f20cd4c8911133fff89"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d46434dd2ae33a38ebd99fc2fbb8eacceb842375"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "3eaf02b635cad7929a64c6caddc64bedab760743a7c2b624ef7e3c1911498db2"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b96ac55e4bb1d9912cff077d7ce48e6c44b96d5a"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "29cf6e662877c2701137429a8f62314cdee370f044435c35779b4ebb75c45eaf"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "13671360bcfdb3eebfe7405749727acd2ec1253b"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "78a38e79dda310dbf06a53d9589c9d9a6acc62c650047e34e3685c7a7eacbbb0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "ded65073521fb0028cc1f450e34f8a3258f21aea"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c8a24c2a97f09b860addaabf8d4904204480237fb8d351b83fc977170305f408"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "561cd77c014ab8c61f49d4e269b279a7f4a75b9f"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "4854ca7d567787cdbf4c3d364e965ce7d521f4417d7d9939b61c30f64b362488"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "87d5925de2f482d77414d29142fa96127f5e4609"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "8b6b23834c51242ce1cfdbbbd64b9a486ddfbd323140fd8fcc3c2cf95f3babdf"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "c624cd0708765663ba91f23aa885ac0340b5ca34"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "60d3caf8bda1038c3b803c67a484ca53826f4d2183973787470d32313f668ef1"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "d75cbb1ea3aab38e6df989cbd9a95c073526c4cf"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "45a4f19eceaa50b02c56dd5d8c5c25df80c3dbf4b526d1a4257121933e70cf2d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "c7de00244505f97ce9dfefe674ffef97e3e965bf"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "0a37394cfc34cbf3fe0f058dabb1463d33ade8ed391ab4c605ae63ce93f48412"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "9f9b124c3bc56e3f2f4793b9b3cfbc56dafa0613"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "ff7b6f3cf22a352869478f386781ee417c57a7554f70d5a38abdde84894d56f9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "01c4ca997d7c930833b6e53c07d135b2a15d58ab"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "4d845e739173300f098102752f4eed1872a4cec1ad28464d4595d19a8e7922f9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "6b70c1c45c8e8239d81ccf9acc221de291cc3768"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "31dd1c88fdfe35c7e76acb52ba51a3dfa08f0c2e5e1f4dbc5031f2815b4801f5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.1+0/SuiteSparse.v7.5.1.x86_64-w64-mingw32.tar.gz"
