[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "cb3ce296392628b52d97cb105296b0ace2e786ed"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "6545fb4a388f7191802d24422c9b950a41cd7b214299cf110ce0e0ce6f962a22"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+6/SuiteSparse.v5.4.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "5d980fa39bbe380c299acd0cca571aebe80725f7"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "ff285260ca9dd052728f50c78b6e531cbe0e80be1b9ee99ff1fdc5623cfd9545"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+6/SuiteSparse.v5.4.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "5843507f68c1b6fbf2833d2a1daaa1d26e0abab1"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "f71a77fc81be589a9523bf2a12eab74b40cb8eb682683c6da35c3700dd0c2d97"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+6/SuiteSparse.v5.4.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "54d2169779c32c49f9965c6e2976a215656c8f38"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "b3288785bf31d3bda9993e69b623c6cff1cbd564f39ac5c21fc8131de1b937de"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+6/SuiteSparse.v5.4.0.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "f431dad56df9825bc3f44fbf322a962f59f06260"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c94655935493338d73e4cc8307f73216545c6ecbbdb2a21f7c5a270542d9e121"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+6/SuiteSparse.v5.4.0.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "ad729026abd6612be033c7f7e94839e50b79b81d"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "0ed2c5f23931e5a682ce30eb6af7d487dc5d594356cac19a0a48e60cc095cbe4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+6/SuiteSparse.v5.4.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "6768c634544dfd07a811c34766d821775685dbe8"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "0a06de1ac2f2f5cb4f318d777b3ffd19f0db86f69a6dd19c7ef107bf4c9cf415"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+6/SuiteSparse.v5.4.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "c4c54907940924b93e9446cfdf20cc4eb8ea399c"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "6f850a3a71f68dbf0bd18880929e80b1b5a2394c9b9d4011531595916379a534"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+6/SuiteSparse.v5.4.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "1ac6591a8adc77abb126a7fdad50723467ccab12"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "f2bfac63697e5b37092656198f2bd3d43b01ce6301575068ab3a11b778e816aa"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+6/SuiteSparse.v5.4.0.x86_64-apple-darwin14.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "7ae633740ceefc56be4bdaf48180a64896c6919f"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "01ebfd4980d8a0837c9c2f791e9af330235bb80b084fb496e7842eac928205be"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+6/SuiteSparse.v5.4.0.x86_64-unknown-freebsd11.1.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "9919dbba0759cb2dc6e9c371640f268794235c8e"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "1b29cdbf86268e36296045f5d50066d19a592033ec0ebae9f577f176a094ec73"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+6/SuiteSparse.v5.4.0.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "db4950b986c58b0e1f7cb1aa9a46055f765526fa"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "40a66ac7485e55de0c54bc01f015900f77919f3639237ded90bfda7876b466eb"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+6/SuiteSparse.v5.4.0.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "62e96d99a561af6845d4ad873622951bb3e119d7"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "c6f688fb1bba1b2b34b11a3dd251b6ea1324c7d7abc378ab60eb0ff85ed54b52"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+6/SuiteSparse.v5.4.0.x86_64-w64-mingw32.tar.gz"
