[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "bc915526a19a2ef46d873179edf8f199a5bcdff9"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "df84624cc83d980c1e67e71d4059b5e6db29dd40aaf720e37b0d420f512ce934"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.arm-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "e46736b7f8dea8acc8b01fa147e616f683c703b9"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "1098554395e31e2c9ae54abe3eaee8f2802d49ae4c83f750648178ab91b150e5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "9cb9bfc3c9c180f192e9f9a9a5f7d51cbf71216a"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "a1e2c16e932d88d76206ca91f9d8a3030ca34dd3688462fc26ea5629f5eb5904"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "516b09e2928e1a0d309e192e4fce97eb92e70cc3"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "4c96f9faf6c26f3066a8c20f6a337ee3ff57e146a5653c28187eb344148e91fe"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "81dfd92817a76d1cc325c54f9c78522dfc2cd8b2"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "d9e6c51a2a1dd2baa1cba0c32aa68083b4f8959212763c159d2bf8128bc859b8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-apple-darwin14.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "f0e1ac988e799404a5e17b291b460af4e15c9cba"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "aafb8ec5d6c1091076530c6e1b2d178506e186e4e69b932898663215603ec421"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "9b2e3088017eff7b938d043d191f87ec81a111c8"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "35819c0d23cc9d1694803b2ca1972941e887e32a688b447f36c86c1341985501"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "e29faca0b662a2b56a161c9ed50a551d7ff22da3"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "4f792e72731ca0308b52acb198f3b6db04c2580b508fe1f3a039763fe0cb4f15"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "67dfffcdd21a4d6e21e60c1bea134464d9de2823"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d7fd2a16660e149e64569e40806d803131fd042273734eaec633f57e95458556"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "2be85a691e66e9d87262d3f24b7255fdb05659b4"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "caf5cbc7a0a7b5a11ecdaeae2661e2e4bb5f2f76a80a9e22706a250deae744c9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "3e99bfed748c1efbb4359424297dce1a03ce2654"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "45d0cf4c1e531e65e59e444dc8c3c8da0ac4c762d5dd4c313d7f4cb53025deaa"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.x86_64-unknown-freebsd11.1.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "5e9821b3c8b3c8c528142b3d6e325815411d0a49"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "08c097f8f84976750282ae06f59b28fc0263efc7747c9a82227fc3ece8c49ce2"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
git-tree-sha1 = "40ecc1771933295598a0a9ef2b57b65a7f5b8f57"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "9c74a00dd4b5a30d73a0e17414b41fc67b4ffeb21dc8af81225eff9b53cddcac"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.4.0+2/SuiteSparse.v5.4.0.arm-linux-musleabihf.tar.gz"
