[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "6b5df2f9fda314aa5e86889e3b3847942cc535d3"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "30b08b60a6c0f3b32bd63222ff6567fe9ab84d1daca116bf1e8a1bc80898b647"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "8c27e45ef21072521056e37510b4cbb006c2fdd8"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "895aa9024765d5b8462596dba61469267840216e93f050ecd69ab6be1e452b89"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "61f48b072dc97673e62f5b0497d8344ca9817ebd"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "08158d3e131c1ab65ff48fe42a5bcb6dd04dfdc700dcc91a5b0ad92d025fdeab"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "095dcc85412f6601a37cf1b6017a1bddc720602b"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "5ffe3e40fab2829e00cebec583dc943cb94cfc25dde69e40e580676ca0ac6557"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f87e7afe3e7b55d4cc0ccbdd49bc5532931692a"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "a44a3e9221cadbb582a55276893590e205db60471f6fa63087f994cd414b0a76"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "def0af6441d2f92d243d4b4162ee0d63c9ed1c88"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "acc303d4646dcdabbef16fb3981de648229cd0432198e9baf9b86d0cd7723073"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9a995544165c5f0f0a29b9f1a978b6e76de7f08b"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "ec9dcbb401ac63e98fc37f952d3304723d24f8449e9c9383255fe7a2ace8c449"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "597c3ef49407243e5f87e8639c49559ee7d3b821"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "951d1ecc1cc7f0d61ffa45e468420d2e5d8747b282b3b7ae61932371f3abe054"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "3e6e977f1517bdc74f5117f02e078377b3a8b1c0"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8b8563df8daad15729a543385ef50a63f93e65faac76880dfbd0098d0dc9984c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "ac96ac368b8d4a1330cfa71b27596e41a3a24b77"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "117b8d35f4b9eb734f9b73b79ecfe8f617c22845cdbb6eef28f7b2c0a58f8c3d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "2a23da47ffeb73dc36e3f8785108ddf3d735bffe"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "17b66dfccd6502f26cd187f3579795808002ff709bd5aff05c4430595181e076"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "6d0d6173d233ab9d1c14eebf351ca51de230b0bc"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "967c0f2cf221d9438eb76b98d95024dea509c7af33cbf8d067024b00d848cdc7"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "c3c47609fc4b1619ad8664b2a305f74fcd52ad5c"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c335fad06e7593444e2b83e7437476958199ccaa5d48211c2bf850c430ca9aef"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "f49e476c6bd89fa3893c54fe88f8d7dbd53da943"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "643409f26d6f6705957614cfc6a0472ea23bd0e93da77abc6dce507d23585835"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "183f157f306623a5175557e2c7954bbed946165d"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "a5f5f3ce7455168f1eb5031e7e17eafa53c092c856d06e111969fd343e80d2f9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "a350ac69ded6f80764310bae0801969f959b1079"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "feecdf3c8576ef4afdf242bd918e24f8e4faa993a61e0b61dbfe57c33ff18a9b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.5.0+0/SuiteSparse.v7.5.0.x86_64-w64-mingw32.tar.gz"
