[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "041c56577527d9cc8e2c8418730068e00672256d"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "918594362ab8fbbacbc3fb09bf71cf29b877e124f043c34a3f4b1df2895750d1"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "34d3b1f8b96751524687a62983abc06c8bf2f40e"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "2206284bd64a640a240e95ea9bde15463d452cb2ce5c32b136ed78dab1811fb1"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "2c6fe1c0078a55d29ab6a1aaab3d5430efbd69fa"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "ef73b74ae159e9256258fbd6a2e9b058f13aefe25850a66fa1294a1b1c224028"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "f22a31e0ab70b119c1273dd6b1d7868843f2c63f"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "02e0d92350a466796562193abb3f2ac7dc97fd0516e1a9b8dc5d23330a75d636"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.aarch64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6e500d654076f6dfdacb13e6f956b1eaa61b227f"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8bcb82bc06227ba83ce287c51a0009dc994d131ae2723c90d800420dbdd8c503"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "24a4af21c62e59ffe54d5d9e3430fd9148d73efa"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "4ba67687777401297cb4cf02590dc897b2088df46021ba5263310240c86c4f82"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c2bea6e2dd896335b6f4920870cadc41ab816a07"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "12b6f72795890ddf25a3ec425b3d4fceb83c9c708bed0e31ea7d8b951cdfd6c4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bee33beafe62c3e77845602f73f59692a3ebc93d"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "8cc64c83ccc6414a1f2a6106644391c58d8b6ddd2f6454a4b9557d2d0f2e61f6"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "069d7a16fe2631df8e11570a9cc91b7764c0e277"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "077ce9b84caa2c828f8d76279e923babda5d6b8a5d30900ff43c432eabfc3455"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "070018218ac1033b407973e80c2aeb0e81f8f7df"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "99be78eade16065532744b4e789783aab73cdc242e3cf5f597d95663716c3f81"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "f72ce2a87c04975be03b342170602c0d7d183536"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "9765af148e6a3be60bc639ca23891b7ee3b2aebfd053bc17908bb0f20c7e90c8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "9fd2f04437e895f8948429a7a2e9348d06bfad87"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "376176b96e7ffeb5e4c3280e1b172db914f9ef4beadc7b8a69a6ee96b6cde137"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "riscv64"
git-tree-sha1 = "f0ba6da1ecd6c17c64e1a27be6281cb95a14d575"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "4fdc184fc3bd57a450750f95d157865a0a5c616a41d41f703e42c72db02a77f1"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.riscv64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "70808a98d905f666a2a7d602cabea42c3ab193dc"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "82ee642b72a061dd53a8cb7228cf7095027152f4cee65223e8752613febbb275"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "9e230e0a139d8a6f1e0fd46cfc9e426f235db210"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "a7c03664690f0b77feffea5d934ff4250c68e0cf7817c450e93cd27a9df904dc"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "f776e957e5062b2a9a3f49f26a8a9b8c777817d8"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "610a24bf2af3851e29bac589acb587461e2635af0cfc2c5ce10dbdf7a683c7d2"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "dcc850106e8f5717327df7f459e00a853274af34"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "22450225cf0091ff6414bbed9ccd03610a942375c11ae323f33517728ea77ea8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "1f6adc823f4ba36e5a356f3b05958e56c6f7bd77"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "19981f7ab110cf23acf1b84ade5f55876fdb7c763ef71992d6490b2f8a27c976"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.11.0+0/SuiteSparse.v7.11.0.x86_64-w64-mingw32.tar.gz"
