[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "1743ab17d8f27ac1b88249c32512360811202674"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "cccb54b576dbc4c30bb13b13230505799d3f68f88deb130633f0aa975e5019d1"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "93855657e27a9dc901b6a0499028491b8ac41ed9"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "ae360ae359a51092f948e44abb404194eb6a8ae9317b138aa2c4047c542e9c74"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "552393c9059dc00218de76a13802c0de2601340a"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "7e2037394c3128db746b20ddb0a744ca912e1ef0c5bd02078cebf1e7bbe1d81f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "252f700a740e0f1936a18399fc3cff7c6f81bc1c"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "62ede6c6285bfb6facbc602e0c1ec66c9fdd370b4b85daebef09fbfdb8f7387c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6974b9087baaf47e181f25fdaf72a010181e4d8d"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "aab344b4e86f7a80df7ed0a4c26f5d044559f8d994508d3e853c863413f2dcd9"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "827e88fbdd7d08fe3aa268d6b892b036dc5a317a"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "f6fb81051b52a181fa65e9676e64c3506076ead9ea5eb3c1a740039310a8c88d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "67fc521abca3c21e53706afbe2c98b3770524e06"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "1784ab311d6189ae2249fc2eee3531a3310777e4b409f80cb48b6d575e771eda"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "ad89a28e79618a07e05702e2f9b934f0be106d53"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "7f33affafed8a20b1e349eddcdd55ed401991c4a313fd82093d2fc2822f54833"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "657c780e0e9044514530079aa796e6075aa54e85"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "cd79ef2cd17536d280a6b2ab47510bcc2f5bdc745f9a518faad3a6a44fcbed3b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "669a7b0fbc8500cde6e593e872efbf637b675662"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "391a6d529ae61df174d01898e435eca4068a5e5eb7c6473291c408e5603e0f37"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "b7bc6611fbd670d3c7cc00d4436e060507c05b68"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "2b08b03f3bbe602b2080e387fe146c706045ba23296db812f2f0fe0b1ef78d11"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "e2221784bc73faf9b4af484ba8bf7ea637157057"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "053fa95832e99bed8d7c2f6ccd46f0da37b106cc9dcd8789eb33b6d220e27d2d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "feaa76e5f05940e3d980c90bf4ca34a63d68da2b"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "23f610e2f1bc4552a90c8d2d214cace37b5f89d982b4fda7a9f2194aabbcaa61"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "258c3ee706f73014657991e27877f982b3954467"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[SuiteSparse.download]]
    sha256 = "4b8b5d37192d3491e202f5c37d5be1d5759442a02bde50eca8073d3fb02021ab"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "d5caa5a49a062fa5f21327219af4636cf5aaaff2"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "0c99fe1bbe27706177b77c34ed5b16d62ef9e5191da9771b76482cbc1cb58515"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "00bf233539b111e82f96eb065725ea6752712087"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "be5dfaf8a1780e071ada4a7904fde74d4ac45690f272186d19b3dc30d868fdcc"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "a77cbda811084c71df57d5f04fef0ce445f0ad5e"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "a69249b037b081a0c13f7e88fc77f1cac56b8e0f839a7ca4e89f1624e765f4da"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v5.10.1+4/SuiteSparse.v5.10.1.x86_64-w64-mingw32.tar.gz"
