[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "48c40dc1444db3d20a09301c698df292783c1917"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "ddf612d11a28ef1d125ed57d3041acd55a815fc58f91b64dda0dd578853a0ff8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.aarch64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "d3ac4dc1bad5c7b27566a87603afed4eb08713ae"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "0938f4645ff04cff503ead86ee79bef9c97ceac85ca1a4fdc44f36e40b15dc8e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.aarch64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "aarch64"
git-tree-sha1 = "394fb8c16b18d95ec6cb130a385e35444bf11211"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "38c00e6b4791ff20c3d0aa6e70e31e33d7ed69bbf541f2a6197dcdd5c58250fa"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.aarch64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3276f5a00d254960c79121107620b1d706d9851f"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "518d53f29aa81596d4b60af95aae8e6927e6dc5f73247250ca72573a16501fb5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.armv6l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ed45f9606c898404958d29fd4a0a59a0a28777dc"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "d7098ef520ca0db503ba1f7e7b426a975cd701e1bc0f41967fb320382c802cba"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.armv6l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e23fa0bf6ba505ff2f7ec455b37d235a38997bb4"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "abcba33a00b43ec86f93511f13c65228be240bdb2462280b69bc31c4d12da524"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.armv7l-linux-gnueabihf.tar.gz"
[[SuiteSparse]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4fe7e08be5c195d29eec1d9ddc5f5027294b6ef5"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "e1bcf2f1bb2e3e3ea46ef6e24e223b111f39703b4d8414b5e8852db710b552ea"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.armv7l-linux-musleabihf.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "eb79c9c621bc69c02c41623546dba64838c78110"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "c9f11241eb7d89da28ed89734f2af2a0b3ce465bb1ef71ed807895e7f1b76e23"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.i686-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "e11f90d0cee6664b417070f929c0e8bb672a6ff7"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "85d39dbee48df94464211b65ee37cb7358865cd0d369c2d863d1bf2c1998b208"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.i686-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "i686"
git-tree-sha1 = "d87a7f15d9a8391b0afbdd5310b1c346af25cef6"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "68d552e179da2d6d78fd18c978d58a06341abaa6a006bdd37d04e5607eac70d3"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.i686-w64-mingw32.tar.gz"
[[SuiteSparse]]
arch = "powerpc64le"
git-tree-sha1 = "5bfe26973056df6143463e3f1767601a4fdf59ea"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "27dc8df95416f493994028076cc4397c30a53ba4b9bca2c4b0073ea79fb46dea"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.powerpc64le-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "d7d07cf104e9f52c8181970ebd1c85eb5933c86e"
os = "macos"

    [[SuiteSparse.download]]
    sha256 = "daf271c25502403bec949024815b7f18ac41d9bbbc56520f28bd5ed82137690f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.x86_64-apple-darwin.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "99a4948e389c64e6fa64d66429f449ee8ceb7a57"
libc = "glibc"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "4784f4f4dfb1c3746749e10cd5826ad35b9711d3ea9ab32c542f663d849fc611"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.x86_64-linux-gnu.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "aca0ebd27ad4d5cb0fc6aadf0b06d2d05e6ff41a"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[SuiteSparse.download]]
    sha256 = "f0c5072067977b7cdb865ce9e6fd8b436e162db8f7377cbfab84578b068eb548"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.x86_64-linux-gnu-sanitize+memory.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "07e819ba304357b403465a55d420b157983b1db5"
libc = "musl"
os = "linux"

    [[SuiteSparse.download]]
    sha256 = "89900d8b8bb2186e8216d15f16bf43ac601c379860e9a9295dc563ec581ab848"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.x86_64-linux-musl.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "15c80a9750efbd9e35e7c196ce7de7cc9dd8dd7a"
os = "freebsd"

    [[SuiteSparse.download]]
    sha256 = "3d72ee9b11c0678a0af564a97006e0de9631a0d4ccfec4eb57688a20d907e1f5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.x86_64-unknown-freebsd.tar.gz"
[[SuiteSparse]]
arch = "x86_64"
git-tree-sha1 = "17ba5c303cfb3a219519ea89ba50c25198cc4147"
os = "windows"

    [[SuiteSparse.download]]
    sha256 = "ccb954396b4d9c2a795e84d051797039e8fa825b99805be2a7009131aab1657e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/download/SuiteSparse-v7.0.1+0/SuiteSparse.v7.0.1.x86_64-w64-mingw32.tar.gz"
