# Autogenerated wrapper script for SuiteSparse_jll for aarch64-apple-darwin
export libamd, libbtf, libcamd, libccolamd, libcholmod, libcolamd, libklu, libldl, librbio, libspqr, libsuitesparseconfig, libumfpack

using libblastrampoline_jll
JLLWrappers.@generate_wrapper_header("SuiteSparse")
JLLWrappers.@declare_library_product(libamd, "@rpath/libamd.2.dylib")
JLLWrappers.@declare_library_product(libbtf, "@rpath/libbtf.1.dylib")
JLLWrappers.@declare_library_product(libcamd, "@rpath/libcamd.2.dylib")
JLLWrappers.@declare_library_product(libccolamd, "@rpath/libccolamd.2.dylib")
JLLWrappers.@declare_library_product(libcholmod, "@rpath/libcholmod.3.dylib")
JLLWrappers.@declare_library_product(libcolamd, "@rpath/libcolamd.2.dylib")
JLLWrappers.@declare_library_product(libklu, "@rpath/libklu.1.dylib")
JLLWrappers.@declare_library_product(libldl, "@rpath/libldl.2.dylib")
JLLWrappers.@declare_library_product(librbio, "@rpath/librbio.2.dylib")
JLLWrappers.@declare_library_product(libspqr, "@rpath/libspqr.2.dylib")
JLLWrappers.@declare_library_product(libsuitesparseconfig, "@rpath/libsuitesparseconfig.5.dylib")
JLLWrappers.@declare_library_product(libumfpack, "@rpath/libumfpack.5.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll)
    JLLWrappers.@init_library_product(
        libamd,
        "lib/libamd.2.4.6.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbtf,
        "lib/libbtf.1.2.6.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcamd,
        "lib/libcamd.2.4.6.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libccolamd,
        "lib/libccolamd.2.9.6.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcholmod,
        "lib/libcholmod.3.0.14.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcolamd,
        "lib/libcolamd.2.9.6.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libklu,
        "lib/libklu.1.3.8.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libldl,
        "lib/libldl.2.2.6.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        librbio,
        "lib/librbio.2.2.6.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libspqr,
        "lib/libspqr.2.0.9.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsuitesparseconfig,
        "lib/libsuitesparseconfig.5.10.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libumfpack,
        "lib/libumfpack.5.7.9.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
