# Autogenerated wrapper script for SuiteSparse_jll for x86_64-w64-mingw32
export libamd, libbtf, libcamd, libccolamd, libcholmod, libcolamd, libklu, libldl, librbio, libspqr, libsuitesparse_wrapper, libsuitesparseconfig, libumfpack

using libblastrampoline_jll
JLLWrappers.@generate_wrapper_header("SuiteSparse")
JLLWrappers.@declare_library_product(libamd, "libamd.dll")
JLLWrappers.@declare_library_product(libbtf, "libbtf.dll")
JLLWrappers.@declare_library_product(libcamd, "libcamd.dll")
JLLWrappers.@declare_library_product(libccolamd, "libccolamd.dll")
JLLWrappers.@declare_library_product(libcholmod, "libcholmod.dll")
JLLWrappers.@declare_library_product(libcolamd, "libcolamd.dll")
JLLWrappers.@declare_library_product(libklu, "libklu.dll")
JLLWrappers.@declare_library_product(libldl, "libldl.dll")
JLLWrappers.@declare_library_product(librbio, "librbio.dll")
JLLWrappers.@declare_library_product(libspqr, "libspqr.dll")
JLLWrappers.@declare_library_product(libsuitesparse_wrapper, "libsuitesparse_wrapper.dll")
JLLWrappers.@declare_library_product(libsuitesparseconfig, "libsuitesparseconfig.dll")
JLLWrappers.@declare_library_product(libumfpack, "libumfpack.dll")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll)
    JLLWrappers.@init_library_product(
        libamd,
        "bin\\libamd.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbtf,
        "bin\\libbtf.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcamd,
        "bin\\libcamd.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libccolamd,
        "bin\\libccolamd.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcholmod,
        "bin\\libcholmod.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcolamd,
        "bin\\libcolamd.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libklu,
        "bin\\libklu.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libldl,
        "bin\\libldl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        librbio,
        "bin\\librbio.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libspqr,
        "bin\\libspqr.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsuitesparse_wrapper,
        "bin\\libsuitesparse_wrapper.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsuitesparseconfig,
        "bin\\libsuitesparseconfig.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libumfpack,
        "bin\\libumfpack.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
